development:
  adapter: postgresql
  database: tweet_me_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: tweet_me_test
  pool: 5
  host: localhost
  user: postgres
  timeout: 5000

production:
  adapter: postgresql
  database: tweet_me_production
  pool: 5
  timeout: 5000
